spring.application.name=company-analysis
# H2 데이터베이스 (파일 저장 방식 - 서버 꺼도 데이터 유지)
spring.datasource.url=jdbc:h2:file:./data/companydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 웹 콘솔 켜기
spring.h2.console.enabled=true

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DART API
dart.api-key=c05dd709712238e242bcfe80a7f96451932d305f

# 한국투자증권 API
kis.app-key=PSiJjjq7QOTqfpLlrTAeQvEmmcJvzDIK9UwS
kis.app-secret=CrFkxfGiKwO4FhVV+YBrfDRr09n+MMIcC0XRHT14Jr4LZoxZgBQ9xRCzBDF21wA3FZDbv8jzR3gZ01x/0Iv+y+b2wRiwYujw5Fn8o5xiQ9xzIxbO6D7z0q7Dos+WUYCPbmTeb+03kwizvB9WmG9ABXQc9f5O1VJ8yjYP/pWeIg+16HhaoGA=
kis.account-no=44831383
kis.base-url=https://openapi.koreainvestment.com:9443
